"""
Database models for the Jarvis AI Assistant — Day 3.

Model hierarchy:
  User (Django built-in)
    └── UserProfile      — extended profile (OneToOne)
    └── ChatSession      — a named conversation thread
          └── ChatMessage — individual turns in a session
    └── Note             — freeform notes
    └── Reminder         — time-bound reminders
    └── UserMemory       — persistent key-value AI context store
    └── ActivityLog      — immutable audit trail of user actions
"""

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


# ---------------------------------------------------------------------------
# Shared abstract base — adds created_at / updated_at to any model
# ---------------------------------------------------------------------------
class TimeStampedModel(models.Model):
    """
    Abstract base class that automatically records creation and
    last-modification timestamps on every subclass.
    """
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# ===========================================================================
# 1. UserProfile
# ===========================================================================
class UserProfile(TimeStampedModel):
    """
    One-to-one extension of Django's built-in User model.
    Stores application-specific preferences and metadata.
    """

    THEME_CHOICES = [
        ('dark',  'Dark Mode'),
        ('light', 'Light Mode'),
        ('auto',  'Auto (System)'),
    ]

    LANGUAGE_CHOICES = [
        ('en', 'English'),
        ('es', 'Spanish'),
        ('fr', 'French'),
        ('de', 'German'),
        ('hi', 'Hindi'),
    ]

    # Core link
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile',
        help_text='The Django user this profile belongs to.',
    )

    # Display
    avatar = models.ImageField(
        upload_to='avatars/',
        null=True,
        blank=True,
        help_text='Optional profile picture.',
    )
    bio = models.TextField(
        blank=True,
        default='',
        help_text='Short user biography or tagline.',
    )

    # Preferences
    theme = models.CharField(
        max_length=10,
        choices=THEME_CHOICES,
        default='dark',
    )
    preferred_language = models.CharField(
        max_length=10,
        choices=LANGUAGE_CHOICES,
        default='en',
    )
    timezone = models.CharField(
        max_length=50,
        default='UTC',
        help_text='IANA timezone string, e.g. "Asia/Kolkata".',
    )

    # Feature toggles
    voice_enabled = models.BooleanField(
        default=True,
        help_text='Whether the voice assistant feature is active.',
    )
    notifications_enabled = models.BooleanField(
        default=True,
        help_text='Whether browser/email notifications are enabled.',
    )

    # Stats (denormalised counters for quick display)
    total_messages = models.PositiveIntegerField(default=0)
    total_sessions  = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name        = 'User Profile'
        verbose_name_plural = 'User Profiles'
        ordering            = ['-created_at']

    def __str__(self):
        return f'Profile({self.user.username})'

    def get_display_name(self):
        """Return full name if available, otherwise username."""
        return self.user.get_full_name() or self.user.username


# ===========================================================================
# 2. ChatSession
# ===========================================================================
class ChatSession(TimeStampedModel):
    """
    A named conversation thread between a user and Jarvis.
    Each session groups a sequence of ChatMessages.
    """

    STATUS_CHOICES = [
        ('active',   'Active'),
        ('archived', 'Archived'),
        ('deleted',  'Deleted'),
    ]

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='chat_sessions',
        help_text='Owner of this chat session.',
    )
    title = models.CharField(
        max_length=255,
        default='New Chat',
        help_text='Human-readable title for the session.',
    )
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='active',
    )
    # Cached summary generated by AI (populated in a later sprint)
    summary = models.TextField(
        blank=True,
        default='',
        help_text='Auto-generated summary of the conversation.',
    )
    # Total tokens used — for future API cost tracking
    total_tokens = models.PositiveIntegerField(
        default=0,
        help_text='Cumulative token count for this session.',
    )
    last_message_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text='Timestamp of the most recent message.',
    )

    class Meta:
        verbose_name        = 'Chat Session'
        verbose_name_plural = 'Chat Sessions'
        ordering            = ['-last_message_at', '-created_at']

    def __str__(self):
        return f'[{self.user.username}] {self.title} ({self.get_status_display()})'

    def message_count(self):
        """Return the number of messages in this session."""
        return self.messages.count()


# ===========================================================================
# 3. ChatMessage
# ===========================================================================
class ChatMessage(models.Model):
    """
    A single turn (user or assistant) within a ChatSession.
    Not time-stamped via TimeStampedModel so we use a single
    created_at only — messages are immutable once written.
    """

    ROLE_CHOICES = [
        ('user',      'User'),
        ('assistant', 'Jarvis AI'),
        ('system',    'System'),
    ]

    session = models.ForeignKey(
        ChatSession,
        on_delete=models.CASCADE,
        related_name='messages',
        help_text='Parent session this message belongs to.',
    )
    role = models.CharField(
        max_length=20,
        choices=ROLE_CHOICES,
        default='user',
        help_text='Who sent this message.',
    )
    content = models.TextField(
        help_text='Raw text content of the message.',
    )
    # Token count for this individual message
    token_count = models.PositiveIntegerField(
        default=0,
        help_text='Number of tokens in this message.',
    )
    # Was this message flagged as sensitive/error?
    is_flagged = models.BooleanField(
        default=False,
        help_text='Flagged for review by system or moderator.',
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name        = 'Chat Message'
        verbose_name_plural = 'Chat Messages'
        ordering            = ['created_at']

    def __str__(self):
        preview = self.content[:60] + '…' if len(self.content) > 60 else self.content
        return f'[{self.get_role_display()}] {preview}'


# ===========================================================================
# 4. Note
# ===========================================================================
class Note(TimeStampedModel):
    """
    A freeform note created by the user, optionally associated with
    a chat session. Supports tagging and pinning.
    """

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='notes',
    )
    session = models.ForeignKey(
        ChatSession,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='notes',
        help_text='Optional: note created during this chat session.',
    )

    title = models.CharField(
        max_length=255,
        default='Untitled Note',
    )
    content = models.TextField(
        help_text='Main body of the note (supports Markdown).',
    )
    tags = models.CharField(
        max_length=500,
        blank=True,
        default='',
        help_text='Comma-separated tag list, e.g. "work,ideas,urgent".',
    )
    is_pinned = models.BooleanField(
        default=False,
        help_text='Pinned notes appear at the top of the list.',
    )
    is_archived = models.BooleanField(
        default=False,
    )

    class Meta:
        verbose_name        = 'Note'
        verbose_name_plural = 'Notes'
        ordering            = ['-is_pinned', '-updated_at']

    def __str__(self):
        return f'[{self.user.username}] {self.title}'

    def tag_list(self):
        """Return tags as a Python list."""
        return [t.strip() for t in self.tags.split(',') if t.strip()]


# ===========================================================================
# 5. Reminder
# ===========================================================================
class Reminder(TimeStampedModel):
    """
    A time-bound reminder that belongs to a user.
    The actual notification dispatch will be handled by Celery (future sprint).
    """

    PRIORITY_CHOICES = [
        ('low',    'Low'),
        ('medium', 'Medium'),
        ('high',   'High'),
        ('urgent', 'Urgent'),
    ]

    STATUS_CHOICES = [
        ('pending',   'Pending'),
        ('sent',      'Sent'),
        ('dismissed', 'Dismissed'),
        ('snoozed',   'Snoozed'),
    ]

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='reminders',
    )
    session = models.ForeignKey(
        ChatSession,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='reminders',
        help_text='Optional: reminder created during this chat session.',
    )

    title = models.CharField(max_length=255)
    description = models.TextField(
        blank=True,
        default='',
        help_text='Optional additional context for this reminder.',
    )
    remind_at = models.DateTimeField(
        help_text='When to trigger this reminder.',
    )
    priority = models.CharField(
        max_length=10,
        choices=PRIORITY_CHOICES,
        default='medium',
    )
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='pending',
    )
    is_recurring = models.BooleanField(
        default=False,
    )
    recurrence_rule = models.CharField(
        max_length=100,
        blank=True,
        default='',
        help_text='iCal RRULE string, e.g. "FREQ=DAILY;INTERVAL=1".',
    )
    snoozed_until = models.DateTimeField(
        null=True,
        blank=True,
        help_text='If snoozed, the new trigger time.',
    )

    class Meta:
        verbose_name        = 'Reminder'
        verbose_name_plural = 'Reminders'
        ordering            = ['remind_at']

    def __str__(self):
        return (
            f'[{self.user.username}] {self.title} '
            f'@ {self.remind_at.strftime("%Y-%m-%d %H:%M")} '
            f'({self.get_status_display()})'
        )

    def is_overdue(self):
        """Return True if the reminder is past its due time and still pending."""
        return self.status == 'pending' and self.remind_at < timezone.now()


# ===========================================================================
# 6. UserMemory
# ===========================================================================
class UserMemory(TimeStampedModel):
    """
    Persistent key-value store for AI context about a user.
    Jarvis uses this to personalise responses across sessions.

    Examples:
      key='user_name_preference', value='Call me Alex'
      key='dietary_preference',   value='vegetarian'
      key='work_role',            value='software engineer'
    """

    CATEGORY_CHOICES = [
        ('preference', 'Preference'),
        ('fact',       'Personal Fact'),
        ('goal',       'Goal'),
        ('context',    'Context'),
        ('other',      'Other'),
    ]

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='memories',
    )
    key = models.CharField(
        max_length=120,
        help_text='Short snake_case identifier, e.g. "preferred_name".',
    )
    value = models.TextField(
        help_text='The remembered value or fact.',
    )
    category = models.CharField(
        max_length=20,
        choices=CATEGORY_CHOICES,
        default='other',
    )
    confidence = models.FloatField(
        default=1.0,
        help_text='AI confidence score (0.0–1.0) for this memory entry.',
    )
    is_active = models.BooleanField(
        default=True,
        help_text='Inactive memories are ignored by the AI but kept for audit.',
    )
    source_session = models.ForeignKey(
        ChatSession,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='memories',
        help_text='Session in which this memory was first recorded.',
    )

    class Meta:
        verbose_name        = 'User Memory'
        verbose_name_plural = 'User Memories'
        ordering            = ['-updated_at']
        # Each user can have at most one active entry per key
        unique_together = [('user', 'key')]

    def __str__(self):
        active_label = '' if self.is_active else ' [inactive]'
        return f'[{self.user.username}] {self.key}: {self.value[:60]}{active_label}'


# ===========================================================================
# 7. ActivityLog
# ===========================================================================
class ActivityLog(models.Model):
    """
    Immutable audit trail of significant user actions within the app.
    Records are never updated — only inserted and (soft-)deleted.

    Examples of action values:
      'register', 'login', 'logout',
      'create_note', 'delete_note',
      'create_reminder', 'dismiss_reminder',
      'start_chat', 'send_message',
    """

    ACTION_CHOICES = [
        # Auth
        ('register',          'Registered'),
        ('login',             'Logged In'),
        ('logout',            'Logged Out'),
        # Chat
        ('start_chat',        'Started Chat Session'),
        ('send_message',      'Sent Message'),
        ('archive_chat',      'Archived Chat'),
        # Notes
        ('create_note',       'Created Note'),
        ('update_note',       'Updated Note'),
        ('delete_note',       'Deleted Note'),
        ('pin_note',          'Pinned Note'),
        # Reminders
        ('create_reminder',   'Created Reminder'),
        ('dismiss_reminder',  'Dismissed Reminder'),
        ('snooze_reminder',   'Snoozed Reminder'),
        # Profile
        ('update_profile',    'Updated Profile'),
        ('update_settings',   'Changed Settings'),
        # Other
        ('other',             'Other'),
    ]

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='activity_logs',
        help_text='The user who performed the action.',
    )
    action = models.CharField(
        max_length=40,
        choices=ACTION_CHOICES,
        default='other',
        db_index=True,
    )
    description = models.TextField(
        blank=True,
        default='',
        help_text='Human-readable description of the action.',
    )
    # Optional JSON-compatible metadata (e.g. {"note_id": 42})
    metadata = models.JSONField(
        default=dict,
        blank=True,
        help_text='Arbitrary JSON payload for additional context.',
    )
    ip_address = models.GenericIPAddressField(
        null=True,
        blank=True,
        help_text='Client IP address at the time of the action.',
    )
    user_agent = models.TextField(
        blank=True,
        default='',
        help_text='Browser / client User-Agent string.',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
    )

    class Meta:
        verbose_name        = 'Activity Log'
        verbose_name_plural = 'Activity Logs'
        ordering            = ['-created_at']

    def __str__(self):
        ts = self.created_at.strftime('%Y-%m-%d %H:%M')
        return f'[{ts}] {self.user.username} → {self.get_action_display()}'


# ===========================================================================
# 8. UserDocument — Knowledge Vault (Day 7)
# ===========================================================================
class UserDocument(TimeStampedModel):
    """
    An uploaded document stored in the Knowledge Vault.
    Text is extracted on upload and made available to Jarvis for Q&A.
    Supported formats: PDF, DOCX, PPTX, TXT.
    """

    FILE_TYPE_CHOICES = [
        ('pdf',  'PDF Document'),
        ('docx', 'Word Document'),
        ('pptx', 'PowerPoint'),
        ('txt',  'Text File'),
    ]

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='documents',
    )
    title             = models.CharField(max_length=255, help_text='Display name.')
    original_filename = models.CharField(max_length=255, blank=True, default='')
    file              = models.FileField(upload_to='documents/%Y/%m/')
    file_type         = models.CharField(max_length=10, choices=FILE_TYPE_CHOICES)
    file_size         = models.PositiveIntegerField(default=0, help_text='Bytes.')
    extracted_text    = models.TextField(
        blank=True,
        default='',
        help_text='Extracted plaintext used by AI.',
    )
    is_processed      = models.BooleanField(default=False)

    class Meta:
        verbose_name        = 'User Document'
        verbose_name_plural = 'User Documents'
        ordering            = ['-created_at']

    def __str__(self):
        return f'[{self.user.username}] {self.title}'

    def file_size_display(self):
        s = self.file_size
        if s < 1024:         return f'{s} B'
        if s < 1024 * 1024:  return f'{s / 1024:.1f} KB'
        return f'{s / (1024 * 1024):.1f} MB'

    @property
    def icon(self):
        return {
            'pdf':  'bi-file-earmark-pdf-fill',
            'docx': 'bi-file-earmark-word-fill',
            'pptx': 'bi-file-earmark-ppt-fill',
            'txt':  'bi-file-earmark-text-fill',
        }.get(self.file_type, 'bi-file-earmark-fill')


# ===========================================================================
# 9. VoiceSettings — Per-user voice preferences (Day 7)
# ===========================================================================
class VoiceSettings(TimeStampedModel):
    """Stores each user's voice assistant preferences server-side."""

    GENDER_CHOICES = [
        ('female', 'Female'),
        ('male',   'Male'),
    ]
    LANGUAGE_CHOICES = [
        ('en-IN', 'English (India)'),
        ('en-GB', 'English (UK)'),
        ('en-US', 'English (US)'),
        ('kn-IN', 'Kannada'),
        ('mixed', 'Mixed (Kannada + English)'),
    ]

    user         = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='voice_settings',
    )
    voice_gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default='female')
    language     = models.CharField(max_length=10, choices=LANGUAGE_CHOICES, default='en-IN')
    auto_speak   = models.BooleanField(default=True)
    speech_rate  = models.FloatField(default=1.0, help_text='Range 0.5–2.0')
    speech_pitch = models.FloatField(default=1.1, help_text='Range 0.0–2.0')

    class Meta:
        verbose_name        = 'Voice Settings'
        verbose_name_plural = 'Voice Settings'

    def __str__(self):
        return f'VoiceSettings({self.user.username})'
