# Generated by Django 6.0.6 on 2026-06-05 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', 'Registered'), ('login', 'Logged In'), ('logout', 'Logged Out'), ('start_chat', 'Started Chat Session'), ('send_message', 'Sent Message'), ('archive_chat', 'Archived Chat'), ('create_note', 'Created Note'), ('update_note', 'Updated Note'), ('delete_note', 'Deleted Note'), ('pin_note', 'Pinned Note'), ('create_reminder', 'Created Reminder'), ('dismiss_reminder', 'Dismissed Reminder'), ('snooze_reminder', 'Snoozed Reminder'), ('update_profile', 'Updated Profile'), ('update_settings', 'Changed Settings'), ('other', 'Other')], db_index=True, default='other', max_length=40)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description of the action.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary JSON payload for additional context.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address at the time of the action.', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser / client User-Agent string.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(help_text='The user who performed the action.', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='New Chat', help_text='Human-readable title for the session.', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('summary', models.TextField(blank=True, default='', help_text='Auto-generated summary of the conversation.')),
                ('total_tokens', models.PositiveIntegerField(default=0, help_text='Cumulative token count for this session.')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent message.', null=True)),
                ('user', models.ForeignKey(help_text='Owner of this chat session.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Jarvis AI'), ('system', 'System')], default='user', help_text='Who sent this message.', max_length=20)),
                ('content', models.TextField(help_text='Raw text content of the message.')),
                ('token_count', models.PositiveIntegerField(default=0, help_text='Number of tokens in this message.')),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged for review by system or moderator.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(help_text='Parent session this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Untitled Note', max_length=255)),
                ('content', models.TextField(help_text='Main body of the note (supports Markdown).')),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated tag list, e.g. "work,ideas,urgent".', max_length=500)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned notes appear at the top of the list.')),
                ('is_archived', models.BooleanField(default=False)),
                ('session', models.ForeignKey(blank=True, help_text='Optional: note created during this chat session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='assistant.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional additional context for this reminder.')),
                ('remind_at', models.DateTimeField(help_text='When to trigger this reminder.')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('dismissed', 'Dismissed'), ('snoozed', 'Snoozed')], default='pending', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, default='', help_text='iCal RRULE string, e.g. "FREQ=DAILY;INTERVAL=1".', max_length=100)),
                ('snoozed_until', models.DateTimeField(blank=True, help_text='If snoozed, the new trigger time.', null=True)),
                ('session', models.ForeignKey(blank=True, help_text='Optional: reminder created during this chat session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='assistant.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'ordering': ['remind_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, help_text='Optional profile picture.', null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, default='', help_text='Short user biography or tagline.')),
                ('theme', models.CharField(choices=[('dark', 'Dark Mode'), ('light', 'Light Mode'), ('auto', 'Auto (System)')], default='dark', max_length=10)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi')], default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone string, e.g. "Asia/Kolkata".', max_length=50)),
                ('voice_enabled', models.BooleanField(default=True, help_text='Whether the voice assistant feature is active.')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Whether browser/email notifications are enabled.')),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(help_text='The Django user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='Short snake_case identifier, e.g. "preferred_name".', max_length=120)),
                ('value', models.TextField(help_text='The remembered value or fact.')),
                ('category', models.CharField(choices=[('preference', 'Preference'), ('fact', 'Personal Fact'), ('goal', 'Goal'), ('context', 'Context'), ('other', 'Other')], default='other', max_length=20)),
                ('confidence', models.FloatField(default=1.0, help_text='AI confidence score (0.0–1.0) for this memory entry.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive memories are ignored by the AI but kept for audit.')),
                ('source_session', models.ForeignKey(blank=True, help_text='Session in which this memory was first recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='assistant.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Memory',
                'verbose_name_plural': 'User Memories',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
