# Generated by Django 6.0.6 on 2026-06-06 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Display name.', max_length=255)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('pptx', 'PowerPoint'), ('txt', 'Text File')], max_length=10)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Bytes.')),
                ('extracted_text', models.TextField(blank=True, default='', help_text='Extracted plaintext used by AI.')),
                ('is_processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Document',
                'verbose_name_plural': 'User Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voice_gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10)),
                ('language', models.CharField(choices=[('en-IN', 'English (India)'), ('en-GB', 'English (UK)'), ('en-US', 'English (US)'), ('kn-IN', 'Kannada'), ('mixed', 'Mixed (Kannada + English)')], default='en-IN', max_length=10)),
                ('auto_speak', models.BooleanField(default=True)),
                ('speech_rate', models.FloatField(default=1.0, help_text='Range 0.5–2.0')),
                ('speech_pitch', models.FloatField(default=1.1, help_text='Range 0.0–2.0')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Settings',
                'verbose_name_plural': 'Voice Settings',
            },
        ),
    ]
